cortAreasIndexMap = {'superiorfrontal': -1, 
  'posteriorcingulate': -1, 
  'caudalanteriorcingulate': -1, 
  'frontalpole': -1, 
  'rostralanteriorcingulate': -1, 
  'precentral': 'precentral', 
  'lingual': -1, 
  'parsorbitalis': -1, 
  'insula': -1, 
  'transversetemporal': 'planum temporale', 
  'parsopercularis': 'central operculum', 
  'supramarginal': 'supramarginal', 
  'pericalcarine': -1, 
  'lateraloccipital': -1, 
  'unknown': -1, 
  'isthmuscingulate': -1, 
  'cuneus': -1, 
  'paracentral': -1, 
  'medialorbitofrontal': -1, 
  'fusiform': -1, 
  'postcentral': -1, 
  'superiorparietal': 'superior parietal', 
  'inferiortemporal': -1, 
  'lateralorbitofrontal': -1, 
  'precuneus': -1, 
  'rostralmiddlefrontal': -1, 
  'parahippocampal': -1, 
  'caudalmiddlefrontal': -1, 
  'middletemporal': 'middle temporal', 
  'bankssts': -1, 
  'parstriangularis': 'angular', 
  'temporalpole': -1, 
  'superiortemporal': 'superior temporal', 
  'entorhinal': -1, 
  'inferiorparietal': -1}
